services:
  - type: web
    name: dbf-ranking-analyzers
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: HOST
        value: 0.0.0.0
      - key: OPEN_ROUTE
        value: /
